import { Student, WeightHeightRecord, DayAttendanceAndBank, ScoreSheet, CalendarEvent, ActivityPhoto, TeacherProfile, WithdrawalLog } from '../types';
import { DEFAULT_DRIVE_FOLDER_ID } from './helpers';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-01',
    studentCode: '50101',
    prefix: 'เด็กชาย',
    firstName: 'กิตติศักดิ์',
    lastName: 'รักษ์ความดี',
    nickname: 'ภูมิ',
    birthDate: '2014-05-12',
    age: 12,
    gender: 'male',
    livesWith: 'บิดา-มารดา',
    commuteMethod: 'รถโรงเรียน',
    dailyAllowance: 60,
    parentOccupation: 'พนักงานบริษัท',
    parentPhone: '081-234-5678',
    address: '12/4 หมู่ 2 ต.ในเมือง อ.เมือง จ.นครราชสีมา',
    bloodType: 'O',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&auto=format&fit=crop&q=80',
    currentSavings: 450,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-02',
    studentCode: '50102',
    prefix: 'เด็กหญิง',
    firstName: 'ณัชชา',
    lastName: 'เจริญสุข',
    nickname: 'มินนี่',
    birthDate: '2014-08-20',
    age: 12,
    gender: 'female',
    livesWith: 'มารดา',
    commuteMethod: 'เดิน',
    dailyAllowance: 50,
    parentOccupation: 'ค้าขาย',
    parentPhone: '089-876-5432',
    address: '88/1 ถนนมิตรภาพ อ.เมือง',
    bloodType: 'B',
    chronicDisease: 'ภูมิแพ้อากาศ',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    currentSavings: 620,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-03',
    studentCode: '50103',
    prefix: 'เด็กชาย',
    firstName: 'ธนกฤต',
    lastName: 'ศิริรัตน์',
    nickname: 'ต้นกล้า',
    birthDate: '2014-01-15',
    age: 12,
    gender: 'male',
    livesWith: 'ปู่-ย่า',
    commuteMethod: 'รถจักรยานยนต์',
    dailyAllowance: 40,
    parentOccupation: 'เกษตรกร',
    parentPhone: '082-345-6789',
    address: '5 หมู่ 4 ต.โพธิ์กลาง',
    bloodType: 'A',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    currentSavings: 380,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-04',
    studentCode: '50104',
    prefix: 'เด็กหญิง',
    firstName: 'ปภาพินท์',
    lastName: 'คงมั่น',
    nickname: 'พราว',
    birthDate: '2014-11-03',
    age: 11,
    gender: 'female',
    livesWith: 'บิดา-มารดา',
    commuteMethod: 'รถยนต์ส่วนบุคคล',
    dailyAllowance: 80,
    parentOccupation: 'ข้าราชการครู',
    parentPhone: '086-456-7890',
    address: '109/2 ซอยร่วมใจ',
    bloodType: 'AB',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
    currentSavings: 890,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-05',
    studentCode: '50105',
    prefix: 'เด็กชาย',
    firstName: 'ภัทรพล',
    lastName: 'วงศ์สุวรรณ',
    nickname: 'คอปเตอร์',
    birthDate: '2014-04-18',
    age: 12,
    gender: 'male',
    livesWith: 'ตา-ยาย',
    commuteMethod: 'รถโรงเรียน',
    dailyAllowance: 50,
    parentOccupation: 'รับจ้างทั่วไป',
    parentPhone: '084-567-8901',
    address: '44 หมู่ 1 ต.หนองจะบก',
    bloodType: 'O',
    chronicDisease: 'หอบหืด (มีพ่นยา)',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    currentSavings: 310,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-06',
    studentCode: '50106',
    prefix: 'เด็กหญิง',
    firstName: 'วรัญญา',
    lastName: 'วิริยะกุล',
    nickname: 'ใบบัว',
    birthDate: '2014-07-29',
    age: 12,
    gender: 'female',
    livesWith: 'บิดา-มารดา',
    commuteMethod: 'เดิน',
    dailyAllowance: 40,
    parentOccupation: 'ธุรกิจส่วนตัว',
    parentPhone: '083-678-9012',
    address: '23/7 ต.ในเมือง',
    bloodType: 'B',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    currentSavings: 740,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-07',
    studentCode: '50107',
    prefix: 'เด็กชาย',
    firstName: 'ศุภวิชญ์',
    lastName: 'ทองดี',
    nickname: 'วิน',
    birthDate: '2014-09-14',
    age: 11,
    gender: 'male',
    livesWith: 'บิดา',
    commuteMethod: 'รถจักรยานยนต์',
    dailyAllowance: 50,
    parentOccupation: 'ช่างยนต์',
    parentPhone: '085-789-0123',
    address: '15/2 หมู่ 3 ต.หัวทะเล',
    bloodType: 'O',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    currentSavings: 500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-08',
    studentCode: '50108',
    prefix: 'เด็กหญิง',
    firstName: 'สิริกร',
    lastName: 'มณีรัตน์',
    nickname: 'น้ำอิง',
    birthDate: '2014-02-28',
    age: 12,
    gender: 'female',
    livesWith: 'ป้า',
    commuteMethod: 'รถตู้รับส่ง',
    dailyAllowance: 60,
    parentOccupation: 'พนักงานรัฐวิสาหกิจ',
    parentPhone: '087-890-1234',
    address: '67/8 ต.ในเมือง',
    bloodType: 'A',
    chronicDisease: 'แพ้อาหารทะเล',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    currentSavings: 590,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-09',
    studentCode: '50109',
    prefix: 'เด็กชาย',
    firstName: 'อัครเดช',
    lastName: 'ปัญญาวงศ์',
    nickname: 'บอส',
    birthDate: '2014-06-05',
    age: 12,
    gender: 'male',
    livesWith: 'บิดา-มารดา',
    commuteMethod: 'รถยนต์ส่วนบุคคล',
    dailyAllowance: 70,
    parentOccupation: 'วิศวกร',
    parentPhone: '088-901-2345',
    address: '90/11 ต.บ้านเกาะ',
    bloodType: 'AB',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
    currentSavings: 920,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-10',
    studentCode: '50110',
    prefix: 'เด็กหญิง',
    firstName: 'อนัญญา',
    lastName: 'พูลผล',
    nickname: 'ฟ้าใส',
    birthDate: '2014-10-10',
    age: 11,
    gender: 'female',
    livesWith: 'มารดา',
    commuteMethod: 'เดิน',
    dailyAllowance: 40,
    parentOccupation: 'ค้าขาย',
    parentPhone: '089-012-3456',
    address: '3/1 ซอยสุรนารี',
    bloodType: 'O',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    currentSavings: 410,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-11',
    studentCode: '50111',
    prefix: 'เด็กชาย',
    firstName: 'จิรายุ',
    lastName: 'ตั้งใจมั่น',
    nickname: 'เจเจ',
    birthDate: '2014-03-12',
    age: 12,
    gender: 'male',
    livesWith: 'บิดา-มารดา',
    commuteMethod: 'รถโรงเรียน',
    dailyAllowance: 50,
    parentOccupation: 'พนักงานธนาคาร',
    parentPhone: '081-123-4567',
    address: '77/5 ถ.จอมพล',
    bloodType: 'B',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    currentSavings: 650,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-12',
    studentCode: '50112',
    prefix: 'เด็กหญิง',
    firstName: 'พิมพ์มาดา',
    lastName: 'โสภณวิวัฒน์',
    nickname: 'เพลง',
    birthDate: '2014-12-01',
    age: 11,
    gender: 'female',
    livesWith: 'บิดา-มารดา',
    commuteMethod: 'รถยนต์ส่วนบุคคล',
    dailyAllowance: 60,
    parentOccupation: 'เภสัชกร',
    parentPhone: '082-234-5678',
    address: '14/3 ต.จอหอ',
    bloodType: 'A',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80',
    currentSavings: 780,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-13',
    studentCode: '50113',
    prefix: 'เด็กชาย',
    firstName: 'ชยพล',
    lastName: 'แสงสุริยา',
    nickname: 'บีม',
    birthDate: '2014-04-22',
    age: 12,
    gender: 'male',
    livesWith: 'ยาย',
    commuteMethod: 'รถจักรยานยนต์',
    dailyAllowance: 45,
    parentOccupation: 'ค้าขายผลไม้',
    parentPhone: '083-345-6789',
    address: '56 หมู่ 6 ต.มะเริง',
    bloodType: 'O',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1480429370139-e0132c086e2a?w=400&auto=format&fit=crop&q=80',
    currentSavings: 420,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-14',
    studentCode: '50114',
    prefix: 'เด็กหญิง',
    firstName: 'ธนิดา',
    lastName: 'เกียรติขจร',
    nickname: 'ครีม',
    birthDate: '2014-07-15',
    age: 12,
    gender: 'female',
    livesWith: 'บิดา-มารดา',
    commuteMethod: 'รถตู้รับส่ง',
    dailyAllowance: 50,
    parentOccupation: 'พนักงานบริษัท',
    parentPhone: '084-456-7890',
    address: '89/1 ต.ปรุใหญ่',
    bloodType: 'B',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&auto=format&fit=crop&q=80',
    currentSavings: 530,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'std-15',
    studentCode: '50115',
    prefix: 'เด็กชาย',
    firstName: 'พงศกร',
    lastName: 'รุ่งโรจน์สกุล',
    nickname: 'นนท์',
    birthDate: '2014-09-08',
    age: 11,
    gender: 'male',
    livesWith: 'บิดา-มารดา',
    commuteMethod: 'เดิน',
    dailyAllowance: 50,
    parentOccupation: 'พนักงานไปรษณีย์',
    parentPhone: '085-567-8901',
    address: '33/2 ต.ในเมือง',
    bloodType: 'A',
    chronicDisease: 'ไม่มี',
    photoUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&auto=format&fit=crop&q=80',
    currentSavings: 470,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const INITIAL_TEACHER_PROFILE: TeacherProfile = {
  teacherName: 'ครูสมศรี ใจดีงาม',
  schoolName: 'โรงเรียนอนุบาลและประถมศึกษาสาธิต',
  classroomName: 'ชั้นประถมศึกษาปีที่ 5',
  academicYear: '2569',
  adminUsername: 'airfan',
  adminPasswordHash: '456789',
  gasWebAppUrl: 'https://script.google.com/macros/s/AKfycbxNAC_8XCViH4bm1-Qc77U4LKP7KzwHVIpX3pnLhXDO8Rl5ews7NeHgefAQCxurNLXu/exec',
  driveFolderId: DEFAULT_DRIVE_FOLDER_ID,
  lastModifiedTimestamp: new Date().toISOString(),
};

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-01',
    title: 'ประชุมผู้ปกครองภาคเรียนที่ 1',
    date: new Date().toISOString().slice(0, 10),
    startTime: '09:00',
    endTime: '12:00',
    description: 'ชี้แจงแนวทางการจัดการเรียนรู้ นโยบายห้องเรียน และการออมทรัพย์ของนักเรียน',
    color: 'emerald',
    category: 'ประชุม',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'evt-02',
    title: 'ตรวจสุขภาพและวัดสายตาประจำปี',
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 10),
    startTime: '08:30',
    endTime: '11:30',
    description: 'เจ้าหน้าที่สาธารณสุขเข้ามาตรวจสุขภาพช่องปาก ฟัน และสายตานักเรียนทุกคน',
    color: 'blue',
    category: 'สุขภาพ',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'evt-03',
    title: 'กิจกรรมส่งเสริมการอ่านและรักการเรียนรู้',
    date: new Date(Date.now() + 86400000 * 7).toISOString().slice(0, 10),
    startTime: '13:00',
    endTime: '15:30',
    description: 'ประกวดเล่านิทานคุณธรรม และบันทึกยอดนักอ่านประจำสัปดาห์',
    color: 'amber',
    category: 'กิจกรรม',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'evt-04',
    title: 'ส่งคะแนนเก็บระหว่างภาคเรียน',
    date: new Date(Date.now() + 86400000 * 14).toISOString().slice(0, 10),
    startTime: '16:00',
    endTime: '17:00',
    description: 'ส่งผลการประเมินคะแนนเก็บหน่วยการเรียนรู้ที่ 1-3 ให้ฝ่ายวิชาการ',
    color: 'rose',
    category: 'วิชาการ',
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_WEIGHT_HEIGHT: WeightHeightRecord = {
  id: 'wh-initial-01',
  date: new Date().toISOString().slice(0, 10),
  gradeLevel: 'ป.5',
  academicYear: '2569',
  term: '1',
  note: 'บันทึกน้ำหนัก-ส่วนสูงต้นภาคเรียนที่ 1/2569',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  rows: [
    { id: 'r1', order: 1, studentId: 'std-01', studentName: 'เด็กชายกิตติศักดิ์ รักษ์ความดี', gender: 'ชาย', age: 12, weight: 38, height: 146, bmi: 17.8, status: 'สมส่วน' },
    { id: 'r2', order: 2, studentId: 'std-02', studentName: 'เด็กหญิงณัชชา เจริญสุข', gender: 'หญิง', age: 12, weight: 41, height: 148, bmi: 18.7, status: 'สมส่วน' },
    { id: 'r3', order: 3, studentId: 'std-03', studentName: 'เด็กชายธนกฤต ศิริรัตน์', gender: 'ชาย', age: 12, weight: 44, height: 151, bmi: 19.3, status: 'สมส่วน' },
    { id: 'r4', order: 4, studentId: 'std-04', studentName: 'เด็กหญิงปภาพินท์ คงมั่น', gender: 'หญิง', age: 11, weight: 39, height: 145, bmi: 18.5, status: 'สมส่วน' },
    { id: 'r5', order: 5, studentId: 'std-05', studentName: 'เด็กชายภัทรพล วงศ์สุวรรณ', gender: 'ชาย', age: 12, weight: 52, height: 149, bmi: 23.4, status: 'ท้วม' },
    { id: 'r6', order: 6, studentId: 'std-06', studentName: 'เด็กหญิงวรัญญา วิริยะกุล', gender: 'หญิง', age: 12, weight: 37, height: 144, bmi: 17.8, status: 'สมส่วน' },
    { id: 'r7', order: 7, studentId: 'std-07', studentName: 'เด็กชายศุภวิชญ์ ทองดี', gender: 'ชาย', age: 11, weight: 43, height: 150, bmi: 19.1, status: 'สมส่วน' },
    { id: 'r8', order: 8, studentId: 'std-08', studentName: 'เด็กหญิงสิริกร มณีรัตน์', gender: 'หญิง', age: 12, weight: 42, height: 147, bmi: 19.4, status: 'สมส่วน' },
    { id: 'r9', order: 9, studentId: 'std-09', studentName: 'เด็กชายอัครเดช ปัญญาวงศ์', gender: 'ชาย', age: 12, weight: 58, height: 153, bmi: 24.8, status: 'เริ่มอ้วน' },
    { id: 'r10', order: 10, studentId: 'std-10', studentName: 'เด็กหญิงอนัญญา พูลผล', gender: 'หญิง', age: 11, weight: 36, height: 143, bmi: 17.6, status: 'สมส่วน' },
    { id: 'r11', order: 11, studentId: 'std-11', studentName: 'เด็กชายจิรายุ ตั้งใจมั่น', gender: 'ชาย', age: 12, weight: 45, height: 152, bmi: 19.5, status: 'สมส่วน' },
    { id: 'r12', order: 12, studentId: 'std-12', studentName: 'เด็กหญิงพิมพ์มาดา โสภณวิวัฒน์', gender: 'หญิง', age: 11, weight: 40, height: 147, bmi: 18.5, status: 'สมส่วน' },
    { id: 'r13', order: 13, studentId: 'std-13', studentName: 'เด็กชายชยพล แสงสุริยา', gender: 'ชาย', age: 12, weight: 46, height: 151, bmi: 20.2, status: 'สมส่วน' },
    { id: 'r14', order: 14, studentId: 'std-14', studentName: 'เด็กหญิงธนิดา เกียรติขจร', gender: 'หญิง', age: 12, weight: 43, height: 149, bmi: 19.4, status: 'สมส่วน' },
    { id: 'r15', order: 15, studentId: 'std-15', studentName: 'เด็กชายพงศกร รุ่งโรจน์สกุล', gender: 'ชาย', age: 11, weight: 64, height: 154, bmi: 27.0, status: 'อ้วน' }
  ]
};

export const INITIAL_SCORE_SHEET: ScoreSheet = {
  id: 'score-01',
  title: 'วิชาคณิตศาสตร์พื้นฐาน (ค16101)',
  subjectName: 'คณิตศาสตร์พื้นฐาน',
  subjectCode: 'ค16101',
  classroom: 'ชั้นประถมศึกษาปีที่ 5',
  term: '1',
  academicYear: '2569',
  chapterCount: 4,
  gradingSystem: 'thai_standard',
  scores: INITIAL_STUDENTS.map((s, idx) => {
    const ch1 = [5, 4, 5, 4, 3, 5, 4, 5, 4, 3, 4, 5, 4, 5, 3][idx % 15];
    const ch2 = [4, 5, 4, 5, 3, 5, 4, 4, 5, 3, 4, 5, 3, 4, 3][idx % 15];
    const ch3 = [5, 5, 4, 5, 3, 5, 4, 5, 4, 4, 5, 5, 4, 4, 3][idx % 15];
    const ch4 = [4, 5, 3, 5, 4, 4, 4, 4, 5, 3, 5, 5, 4, 5, 4][idx % 15];
    const total = ch1 + ch2 + ch3 + ch4;
    const pct = Number(((total / 20) * 100).toFixed(1));
    const grade = pct >= 80 ? '4' : pct >= 75 ? '3.5' : pct >= 70 ? '3' : pct >= 65 ? '2.5' : pct >= 60 ? '2' : '1.5';
    return {
      studentId: s.id,
      order: idx + 1,
      studentName: `${s.prefix}${s.firstName} ${s.lastName}`,
      chapterScores: { 1: ch1, 2: ch2, 3: ch3, 4: ch4 },
      totalScore: total,
      percentage: pct,
      grade,
    };
  }),
  totalChapters: 4,
  finalExamMaxScore: 30,
  finalExamScores: {
    'std-01': 27,
    'std-02': 29,
    'std-03': 23,
    'std-04': 28,
    'std-05': 20,
    'std-06': 26,
    'std-07': 25,
    'std-08': 27,
    'std-09': 28,
    'std-10': 21,
    'std-11': 26,
    'std-12': 30,
    'std-13': 22,
    'std-14': 25,
    'std-15': 21,
  },
  studentList: INITIAL_STUDENTS.map((s, idx) => ({
    id: `sl-${s.id}`,
    studentId: s.id,
    order: idx + 1,
    name: `${s.prefix}${s.firstName} ${s.lastName} (${s.nickname})`
  })),
  chapters: [
    {
      chapterNumber: 1,
      title: 'บทที่ 1: ห.ร.ม. และ ค.ร.น.',
      maxScorePerItem: 5,
      totalItems: 10,
      weightPercentage: 25,
      scores: {
        'std-01': [5, 4, 5, 4, 5, 4, 5, 5, 4, 5],
        'std-02': [5, 5, 5, 5, 5, 5, 4, 5, 5, 5],
        'std-03': [4, 4, 3, 5, 4, 3, 4, 4, 5, 4],
        'std-04': [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        'std-05': [3, 4, 3, 4, 3, 4, 4, 3, 4, 3],
        'std-06': [5, 5, 4, 5, 5, 4, 5, 4, 5, 5],
        'std-07': [4, 5, 4, 4, 4, 5, 4, 4, 4, 4],
        'std-08': [5, 4, 5, 4, 4, 5, 5, 4, 5, 4],
        'std-09': [4, 4, 5, 4, 5, 4, 4, 5, 4, 5],
        'std-10': [3, 3, 4, 4, 3, 4, 3, 4, 4, 3],
        'std-11': [4, 5, 4, 5, 5, 4, 5, 4, 5, 4],
        'std-12': [5, 5, 5, 4, 5, 5, 4, 5, 5, 5],
        'std-13': [4, 4, 4, 3, 4, 4, 3, 4, 4, 4],
        'std-14': [5, 4, 4, 5, 4, 5, 4, 4, 5, 4],
        'std-15': [3, 4, 3, 3, 4, 3, 4, 4, 3, 4]
      }
    },
    {
      chapterNumber: 2,
      title: 'บทที่ 2: เศษส่วนและการบวก ลบ คูณ หารเศษส่วน',
      maxScorePerItem: 5,
      totalItems: 10,
      weightPercentage: 25,
      scores: {
        'std-01': [4, 5, 4, 5, 4, 4, 5, '-', '-', '-'],
        'std-02': [5, 5, 5, 4, 5, 5, 5, '-', '-', '-'],
        'std-03': [4, 3, 4, 4, 3, 4, 4, '-', '-', '-'],
        'std-04': [5, 5, 5, 5, 5, 5, 5, '-', '-', '-'],
        'std-05': [3, 3, 4, 3, 4, 3, 3, '-', '-', '-'],
        'std-06': [5, 4, 5, 4, 5, 5, 4, '-', '-', '-'],
        'std-07': [4, 4, 4, 4, 5, 4, 4, '-', '-', '-'],
        'std-08': [4, 5, 4, 5, 4, 4, 5, '-', '-', '-'],
        'std-09': [5, 4, 5, 4, 4, 5, 4, '-', '-', '-'],
        'std-10': [3, 4, 3, 4, 3, 3, 4, '-', '-', '-'],
        'std-11': [4, 5, 4, 5, 5, 4, 4, '-', '-', '-'],
        'std-12': [5, 5, 4, 5, 5, 5, 4, '-', '-', '-'],
        'std-13': [3, 4, 4, 3, 4, 3, 4, '-', '-', '-'],
        'std-14': [4, 4, 5, 4, 4, 4, 5, '-', '-', '-'],
        'std-15': [3, 3, 4, 3, 4, 4, 3, '-', '-', '-']
      }
    },
    {
      chapterNumber: 3,
      title: 'บทที่ 3: ทศนิยมและการบวกลบคูณหารทศนิยม',
      maxScorePerItem: 5,
      totalItems: 10,
      weightPercentage: 25,
      scores: {
        'std-01': [5, 5, 4, 5, 5, 4, 5, 5, '-', '-'],
        'std-02': [5, 5, 5, 5, 5, 5, 5, 5, '-', '-'],
        'std-03': [4, 4, 3, 4, 4, 3, 4, 4, '-', '-'],
        'std-04': [5, 5, 5, 5, 5, 5, 5, 5, '-', '-'],
        'std-05': [3, 4, 3, 4, 3, 4, 3, 4, '-', '-'],
        'std-06': [5, 4, 5, 5, 4, 5, 4, 5, '-', '-'],
        'std-07': [4, 4, 4, 5, 4, 4, 4, 5, '-', '-'],
        'std-08': [5, 4, 5, 4, 5, 4, 5, 4, '-', '-'],
        'std-09': [4, 5, 4, 5, 4, 5, 4, 5, '-', '-'],
        'std-10': [4, 3, 4, 3, 4, 3, 4, 3, '-', '-'],
        'std-11': [5, 4, 5, 4, 5, 5, 4, 5, '-', '-'],
        'std-12': [5, 5, 5, 4, 5, 5, 4, 5, '-', '-'],
        'std-13': [4, 4, 3, 4, 4, 3, 4, 4, '-', '-'],
        'std-14': [5, 4, 4, 5, 4, 5, 4, 4, '-', '-'],
        'std-15': [4, 3, 4, 3, 3, 4, 4, 3, '-', '-']
      }
    },
    {
      chapterNumber: 4,
      title: 'บทที่ 4: ร้อยละและอัตราส่วน',
      maxScorePerItem: 5,
      totalItems: 10,
      weightPercentage: 25,
      scores: {
        'std-01': [4, 5, 5, 4, 5, 4, '-', '-', '-', '-'],
        'std-02': [5, 5, 5, 5, 5, 5, '-', '-', '-', '-'],
        'std-03': [3, 4, 4, 3, 4, 4, '-', '-', '-', '-'],
        'std-04': [5, 5, 5, 5, 5, 5, '-', '-', '-', '-'],
        'std-05': [3, 3, 4, 3, 4, 3, '-', '-', '-', '-'],
        'std-06': [5, 4, 5, 4, 5, 4, '-', '-', '-', '-'],
        'std-07': [4, 4, 5, 4, 4, 5, '-', '-', '-', '-'],
        'std-08': [4, 5, 4, 5, 4, 4, '-', '-', '-', '-'],
        'std-09': [5, 4, 4, 5, 5, 4, '-', '-', '-', '-'],
        'std-10': [3, 4, 3, 4, 3, 4, '-', '-', '-', '-'],
        'std-11': [5, 4, 5, 4, 5, 5, '-', '-', '-', '-'],
        'std-12': [5, 5, 4, 5, 5, 5, '-', '-', '-', '-'],
        'std-13': [4, 3, 4, 4, 3, 4, '-', '-', '-', '-'],
        'std-14': [4, 5, 4, 4, 5, 4, '-', '-', '-', '-'],
        'std-15': [3, 4, 3, 4, 3, 3, '-', '-', '-', '-']
      }
    }
  ],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString()
};

export const INITIAL_ACTIVITY_PHOTOS: ActivityPhoto[] = [
  {
    id: 'act-01',
    title: 'กิจกรรมสัปดาห์วิทยาศาสตร์และคณิตศาสตร์แสนสนุก',
    description: 'นักเรียนร่วมทดลองประดิษฐ์จรวดขวดน้ำและเล่นเกมคณิตคิดเร็ว',
    driveUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=1000&auto=format&fit=crop&q=80',
    date: new Date(Date.now() - 86400000 * 2).toISOString().slice(0, 10),
    category: 'วิทยาศาสตร์',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-02',
    title: 'โครงการออมวันละนิด เพื่อชีวิตสดใส',
    description: 'บันทึกการฝากเงินประจำสัปดาห์ของนักเรียนชั้น ป.6/1 สรุปยอดออมสูงทะลุเป้า',
    driveUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1000&auto=format&fit=crop&q=80',
    date: new Date(Date.now() - 86400000 * 5).toISOString().slice(0, 10),
    category: 'การออมทรัพย์',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-03',
    title: 'กิจกรรมบำเพ็ญประโยชน์ ปลูกป่าชุมชน',
    description: 'นักเรียนและผู้ปกครองร่วมกันปลูกต้นไม้รอบบริเวณแปลงเกษตรโรงเรียน',
    driveUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1000&auto=format&fit=crop&q=80',
    date: new Date(Date.now() - 86400000 * 9).toISOString().slice(0, 10),
    category: 'จิตอาสา',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-04',
    title: 'ประกวดคัดลายมือและเรียงความวันแม่แห่งชาติ',
    description: 'ผลงานคัดลายมือตัวบรรจงเต็มบรรทัดและกึ่งบรรทัดของตัวแทนนักเรียน',
    driveUrl: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=1000&auto=format&fit=crop&q=80',
    date: new Date(Date.now() - 86400000 * 12).toISOString().slice(0, 10),
    category: 'ภาษาไทย',
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_WITHDRAWAL_LOGS: WithdrawalLog[] = [
  {
    id: 'w-01',
    studentId: 'std-03',
    studentName: 'เด็กชายธนกฤต ศิริรัตน์',
    date: new Date(Date.now() - 86400000 * 4).toISOString().slice(0, 10),
    time: '11:30',
    amount: 100,
    reason: 'ซื้อสมุดวาดเขียนและสีไม้สำหรับวิชาศิลปะ',
    adminName: 'ครูสมศรี ใจดีงาม',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'w-02',
    studentId: 'std-07',
    studentName: 'เด็กชายศุภวิชญ์ ทองดี',
    date: new Date(Date.now() - 86400000 * 8).toISOString().slice(0, 10),
    time: '14:15',
    amount: 150,
    reason: 'นำไปซื้อรองเท้านักเรียนใหม่เนื่องจากคู่เดิมขาด',
    adminName: 'ครูสมศรี ใจดีงาม',
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  }
];
